version = 1

exclude_patterns = [
  "src/service-worker.ts",
  "src/serviceWorkerRegistration.ts",
  "src/reportWebVitals.ts"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]